spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1003167231049-bokh7r51olilkmfejtskk9ai43a04fhi.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 8080